source ~/.vim/options.vim
source ~/.vim/keybindings.vim
source ~/.vim/plugins.vim
source ~/.vim/filetypes.vim
source ~/.vim/lightline.vim
source ~/.vim/fzf
echom "some configs from https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim"
