source ~/.vim/options.vim
source ~/.vim/keybindings.vim
source ~/.vim/plugins.vim
source ~/.vim/filetypes.vim
source ~/.vim/lightline.vim
source ~/.vim/fzf.vim
source ~/.vim/colors.vim
source ~/.vim/lsp.vim
source ~/.vim/tabline.vim
echom "This is what inspired this config https://github.com/tonybanters/vim"
